### ISSUE TITLE
Couldn't find AttentionLayer

### ISSUE THREAD

**Issue by iamsile** [qiaojingy/SNLI#1]
When I test it, I found it couldn't find AttentionLayer. Something wrong like this:
l_attention = lasagne.layers.AttentionLayer([l_lstm_prem, l_lstm_hypo], K_HIDDEN, mask_input=l_mask_prem)
AttributeError: 'module' object has no attribute 'AttentionLayer'

**Comment by qiaojingy** [comment]
Hi. I just uploaded it. It's in lasagne/layers/dense.py.

**Comment by iamsile** [comment]
Thank you very much!
But there is another problem when I run snli_baseline.py on mac os 10.11

Training ...
Traceback (most recent call last):
  File "snli_baseline.py", line 165, in <module>
    main()
  File "snli_baseline.py", line 137, in main
    avg_cost += train(X_prem, X_prem_mask, X_hypo, X_hypo_mask, y)
  File "/Library/Python/2.7/site-packages/theano/compile/function_module.py", line 871, in **call**
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/Library/Python/2.7/site-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/Library/Python/2.7/site-packages/theano/compile/function_module.py", line 859, in **call**
    outputs = self.fn()
  File "/Library/Python/2.7/site-packages/theano/scan_module/scan_op.py", line 963, in rval
    r = p(n, [x[0] for x in i], o)
  File "/Library/Python/2.7/site-packages/theano/scan_module/scan_op.py", line 952, in <lambda>
    self, node)
  File "theano/scan_module/scan_perform.pyx", line 405, in theano.scan_module.scan_perform.perform (/Users/xxx/.theano/compiledir_Darwin-15.3.0-x86_64-i386-64bit-i386-2.7.10-64/scan_perform/mod.cpp:4316)
  File "/Library/Python/2.7/site-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "theano/scan_module/scan_perform.pyx", line 397, in theano.scan_module.scan_perform.perform (/Users/xxx/.theano/compiledir_Darwin-15.3.0-x86_64-i386-64bit-i386-2.7.10-64/scan_perform/mod.cpp:4193)
ValueError: Input dimension mis-match. (input[0].shape[1] = 300, input[1].shape[1] = 600)
Apply node that caused the error: Elemwise{Composite{((scalar_sigmoid(i0) \* i1) + (scalar_sigmoid(i2) \* tanh(i3)))}}(Subtensor{::, int64:int64:}.0, <TensorType(float32, matrix)>, Subtensor{::, int64:int64:}.0, Subtensor{::, int64:int64:}.0)

I don't understand why the input[0].shape[1] = 300, but input[1].shape[1] = 600. I don't modify anything.
Can you help me?

**Comment by qiaojingy** [comment]
Hi, thanks for pointing it out! I haven't touch the baseline for a while and changed other codes, so there was something wrong with the dimension. Could you try to pull it again? I think it is fixed now.

**Comment by iamsile** [comment]
Thank you!
